-- Temporary RLS bypass for migration
-- Run this in Supabase SQL Editor BEFORE migration

-- Disable RLS temporarily for migration
ALTER TABLE studies DISABLE ROW LEVEL SECURITY;
ALTER TABLE exercises DISABLE ROW LEVEL SECURITY;
ALTER TABLE protocols DISABLE ROW LEVEL SECURITY;
ALTER TABLE progressions DISABLE ROW LEVEL SECURITY;
ALTER TABLE exercise_studies DISABLE ROW LEVEL SECURITY;
ALTER TABLE protocol_exercises DISABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_guidelines DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE quality_metrics DISABLE ROW LEVEL SECURITY;

-- After migration, re-enable with this:
-- ALTER TABLE studies ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE protocols ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE progressions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE exercise_studies ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE protocol_exercises ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE clinical_guidelines ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE quality_metrics ENABLE ROW LEVEL SECURITY;
